lulzsun/RePlays

Classes/Recorders/LibObsRecorder.cs
ClientApp/src/pages/Settings/Capture.tsx

1440p support.
Made video output resolution reflect user settings.

1440p support and output resolution fix

---

Classes/Utils/Helpers.cs

Fixes the thumbnail bug for users in decimal separated countries.

Fixes the thumbnail bug.

---

ClientApp/src/pages/Player.tsx

Fixes #19.
You can now click the bookmark to navigate to it.

fix: issue #19

---

Classes/Recorders/LibObsRecorder.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/pages/Settings/Capture.tsx

* feat: Hardware encoding with NVENC

feat: Hardware encoding and encoder selection.

---

Classes/Recorders/LibObs/Encoder.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/pages/Settings/Capture.tsx

Added automatic detection of available video encoders.

feat: Detect available encoders

---

Classes/Recorders/LibObsRecorder.cs
Classes/Recorders/PlaysLTCRecorder.cs
Classes/Utils/Helpers.cs
Classes/Utils/JSONObjects.cs
Classes/Utils/Messages.cs
Classes/frmMain.cs
ClientApp/public/preload.html
ClientApp/src/index.tsx
ClientApp/src/pages/Settings/Capture.tsx

Allows the selection of audio input/output devices.

feat: Audio device selection

---

Classes/Recorders/LibObsRecorder.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/pages/Settings/Capture.tsx

fix: Use display capture for games that cannot be hooked.

---

Classes/Recorders/BaseRecorder.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Recorders/PlaysLTCRecorder.cs
Classes/Services/DetectionService.cs
Classes/Services/RecordingService.cs
Classes/Utils/Helpers.cs
RePlays.csproj

Moved code relating to detection of games into DetectionService from BaseRecorder and generally cleaned it up a bit. Also removed NHotkey package as it is no longer used.

refactor: Detection logic moved into DetectionService

---

Classes/Recorders/BaseRecorder.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Recorders/PlaysLTCRecorder.cs
Classes/Services/DetectionService.cs
Classes/Services/RecordingService.cs

Causes the screen to black out when focus is lost while using display capture.
Also some code cleanup.

feat: Screen blackout when focus lost

---

Classes/Recorders/BaseRecorder.cs

Wider case match for splash screens #39

fix: Some splash screens not being handled

---

Classes/Recorders/LibObsRecorder.cs
ClientApp/src/App.tsx
ClientApp/src/pages/Player.tsx
ClientApp/src/pages/VideosPage.tsx

Removed game from metadata since it causes confliction with custom game names set in Settings->Detection->"Custom Recorded Games"
This fixes issue #44

Fix: Custom game name capitalization conflicts.

---

Classes/Utils/Compression.cs
Classes/Utils/Messages.cs
ClientApp/src/components/Card.tsx
ClientApp/src/pages/Player.tsx

Enables clip compression! 
(Also includes a bug fix for a mistake in my recent merge)

FEAT: Clip compression

---

Classes/Services/DetectionService.cs

Fixes an issue where the application checks for a window before the application has started.

FIX: Application IntPtr.Zero retry

---

Classes/Services/DetectionService.cs
ClientApp/src/pages/Settings/Capture.tsx

Alternative to automatic capture where only manually whitelisted games will be auto captured.

feat: Whitelist-only mode

---

Classes/Services/DetectionService.cs

FIX: Changed AutoDetectGame to async and IntPtr.Zero cooldown to Task.Delay

---

Classes/Utils/Compression.cs
Classes/Utils/Helpers.cs

- Changed to libx264 (since platforms like Discord can't preview libx265)
- Replaces the original clip
- Displays a notification (DisplayModal) when the compression has finished

IMPR: Multiple compression improvements.

---

ClientApp/src/pages/Player.tsx

Probably the smallest pull request I've ever made.

Changed case on Bookmark icon

---

Classes/Recorders/LibObsRecorder.cs
Classes/Services/BookmarkService.cs
Classes/Services/RecordingService.cs
ClientApp/src/pages/Player.tsx

I really don't know what happened with this pull request... Sorry for the mess :D

Fixes an issue with fast restarts

---

Classes/frmMain.cs

Before - After (For me who uses Swedish)

Changes the UI to the users Windows regional format.

---

ClientApp/src/App.tsx

Backups the bookmarks that gets applied by integrations and hotkeys

---

Classes/Recorders/BaseRecorder.cs
Classes/Recorders/LibObsRecorder.cs

Changed capture_mode to _any_fullscreen_ instead of _window_ if the game is running in Full Screen.

Allows for EasyAntiCheat games to hook

---

Classes/Integrations/Integration.cs
Classes/Integrations/LeagueOfLegendsIntegration.cs
Classes/Integrations/PubgIntegration.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Services/BookmarkService.cs
Classes/Services/IntegrationService.cs
Classes/Services/RecordingService.cs

* Added [PUBG: BATTLEGROUNDS ](https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/) Integration
* Adjusted integration shutdown timing to occur before bookmark (instead of when OBS writes "capture stopped")
* Ensures PUBG files are fully loaded before bookmarks are added

PUBG Integration

---

Classes/Recorders/LibObsRecorder.cs
Classes/Services/RecordingService.cs

Handle access denied exception when accessing HasExited property in Process class by wrapping it in a try-catch block.

Fix: Access Denied exception

---

Classes/Integrations/PubgIntegration.cs

The new PUBG season patch included some encoded Json property names so I've fixed it.
Also removed a useless log

PUBG latest update fix

---

ClientApp/src/pages/Settings/Capture.tsx

Close: https://github.com/lulzsun/RePlays/issues/63

Fix: "Custom" isn't selected in Capture settings #63

---

Classes/Services/DetectionService.cs

"_The extra "." in the file path returned by process.MainModule.FileName is because of the way Windows handles relative paths._"
Fixes issues where windows would add random \\.\ to directories.
Caches the nonGameDetections in a HashMap.
Thanks to Rumrobot#5735 for providing great support :)
This should have been two different MRs...

fix/feat: Blacklisted game fix & nonGameDetections cache

---

RePlays.csproj
build-libobs.cmd

Please make sure to double-check. I'm not skilled enough to test it locally.

Updated OBS to 29.1.1

---

Classes/Recorders/LibObs/Obs.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Utils/Helpers.cs
Classes/Utils/JSONObjects.cs
Classes/Utils/Messages.cs
ClientApp/src/components/AudioDevice.tsx
ClientApp/src/index.tsx
ClientApp/src/pages/Settings/Capture.tsx

feat: Added NVIDIA Noise Removal integration

---

Classes/Utils/Messages.cs
Classes/Utils/Updater.cs
ClientApp/src/pages/Settings/General.tsx

Added update progress

---

Classes/Integrations/LeagueOfLegendsIntegration.cs
Classes/Recorders/LibObsRecorder.cs
Classes/Utils/Helpers.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/components/Card.tsx
ClientApp/src/index.tsx
ClientApp/src/pages/VideosPage.tsx

Part of #108. Requested by @byotta

Added League Of Legends stats to Session card

---

Resources/detections/gameDetections.json

Not tested, but the file structure is the same as FiveM.

RedM added to gameDetections.json

---

Classes/frmMain.cs

Fixes an issue where the application wouldn't exit properly because of an active thread.

fix: Issue where application wouldn't exit

---

Classes/Utils/Compression.cs
Classes/Utils/Messages.cs
ClientApp/src/components/Card.tsx
ClientApp/src/components/CompressModal.tsx
ClientApp/src/components/DropDownMenu.tsx

Added the ability to select compression preset, see: [FFMPEG](https://trac.ffmpeg.org/wiki/Encode/H.264#Preset)

feat: Compression selection

---

Classes/Program.cs
Classes/Services/KeybindService.cs
Classes/Services/Keybinds/BookmarkKeybind.cs
Classes/Services/Keybinds/Keybind.cs
Classes/Services/Keybinds/RecordingKeybind.cs
Classes/Utils/Messages.cs
RePlays.csproj

Using SharpHook nuget package to handle cross-platform keybinds. 
This will most likely require users to edit their binds.

feat: Implement cross-platform keybinds

---

Classes/Services/UploadService.cs
Classes/Uploaders/BaseUploader.cs
Classes/Uploaders/CustomUploader.cs
Classes/Uploaders/LocalFolderUploader.cs
Classes/Uploaders/RePlaysUploader.cs
Classes/Uploaders/StreamableUploader.cs
Classes/Utils/Messages.cs
ClientApp/src/components/UploadModal.tsx
ClientApp/src/internationalization/locales/de.json
ClientApp/src/internationalization/locales/en.json
ClientApp/src/internationalization/locales/es.json
ClientApp/src/internationalization/locales/fr.json
ClientApp/src/internationalization/locales/it.json
ClientApp/src/internationalization/locales/pt.json

Adds a Public checkbox which lets the user choose if the video should be public or not. 
Implemented for the RePlays Upload website.

Adds a "Public" checkbox to Upload module

---

Classes/Integrations/LeagueOfLegendsIntegration.cs
ClientApp/src/components/Card.tsx

1. Fixed League of Legends integration
2. Fixed Fiddlesticks image

Fixed League of Legends integration

---

Classes/Program.cs
Classes/WindowsInterface.cs
RePlays.csproj
RePlays.sln

Added a _PrevSize Variable to Program in order to restore the previous size

fix(app): #154 Fixed Window Size when restoring window

---

Classes/Integrations/LeagueOfLegendsIntegration.cs
ClientApp/src/components/Card.tsx
ClientApp/src/integrations/league.ts

Fixes League Of Legends markers

---

ClientApp/src/components/Card.tsx

This replaces all % with %25 for urls.
This should make sure that games with a % won't be accidentally encoded as being a percentage encoding.
Sanitise game names with % for urls linking or accessing web server assets.
Closes #204

Sanitise game names with special characters.

---

Classes/Recorders/LibObsRecorder.cs
Classes/Utils/Messages.cs

- Added AV1 support
Suggested in #209 by @hl2jeep

AV1 Support

---

Classes/Utils/Helpers.cs
Classes/Utils/JSONObjects.cs
Classes/Utils/Messages.cs
ClientApp/src/components/HelpSymbol.tsx
ClientApp/src/index.tsx
ClientApp/src/internationalization/locales/en.json
ClientApp/src/pages/Player.tsx
ClientApp/src/pages/Settings/Capture.tsx

- Added precise clipping.
- Added progress bar for clip creation.
- Added a HelpSymbol component.
This issue was reported by [Rumrobot](https://discord.com/channels/654698116917886986/654699568528621570/1232076717968064552) and [Paulchief](https://discord.com/channels/654698116917886986/654699568528621570/1204565659690737664).
_Note: This method takes significantly longer to create the clip and is therefore disabled by default._

Precise clipping

---

ClientApp/src/pages/Player.tsx

fix: resolve black bar and overflow issues in bookmark/share/zoom

---

ClientApp/src/App.tsx

refactor: reduce ui reload flash (white page)

---

Resources/detections/gameDetections.json

- Fixes Rainbow Six Siege (Uplay edition)

fix: change rainbow six gameexe

---

Resources/detections/nonGameDetections.json

- Add Minecraft support by removing javaw.exe from blacklist

fix: add Minecraft support

---

Classes/Services/WindowService.cs

In [this commit](https://github.com/lulzsun/RePlays/commit/32117f0750c7308b8857bdd53451560b4d3f7ea6), the QueryDosDevice call was removed, leading to the loss of functionality for converting device paths (`\Device\HarddiskX\`) to drive letter paths (`C:\some\`).
For games with anti-cheat measures, the whitelisting process registers paths using drive letters, but device paths are retrieved from the game process. This mismatch prevents the recording from starting.
Reintroduced the QueryDosDevice call to restore the conversion process from device paths to drive letter paths.
The unhandle exception mentioned in the commit message did not occur in my environment (Windows 10 22H2).

fix: device path conversion

---

Classes/Integrations/CS2.cs

- Added assists and deaths to CS2 integration

feat: add assists and deaths to CS2 integration

---

ClientApp/src/components/VideoSortControls.tsx

Removes this:
https://github.com/user-attachments/assets/ec30a0f3-1cc2-48ec-a258-5e261bf8d4e8

feat: remove hover/active effect for file storage

---

Classes/Uploaders/RePlaysUploader.cs
Classes/Uploaders/StreamableUploader.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/internationalization/locales/en.json
ClientApp/src/pages/Settings/Upload.tsx

- Added a setting to enable/disable auto-opening videos after upload.
_I noticed that users often upload multiple clips simultaneously, and having this setting will help prevent distractions._

feat: add setting to auto-open uploaded videos

---

Classes/Services/DetectionService.cs

We retrieve the game name for Steam games by parsing their respective `.acf` files.  
Each Steam game has an `.acf` file from which we extract the `installdir` to match the running game's path and the `name`, which we set as `gameName`.
If no matching `.acf` files are found for the install path, we fall back to the old method.

feat: improve steam game name

---

Classes/Recorders/LibObsRecorder.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/internationalization/locales/en.json
ClientApp/src/pages/Settings/Capture.tsx

Made bitrate settings more configurable (no longer just a drop down)
Added options for configuring max bitrate for VBR and CQ levels for CQP/CRF
Changed default output file type to mkv

feat: Implement proper handling of different rate controls

---

ClientApp/src/pages/Player.tsx

Before:<br>
<br>
After:<br>
<br>

fix: missing thumbnail in UploadModal

---

Classes/Recorders/LibObsRecorder.cs

Added HEVC NVENC to the supported encoders.

feat: Added HEVC support for NVENC

---

Classes/Utils/JSONObjects.cs
ClientApp/src/App.tsx
ClientApp/src/index.tsx
ClientApp/src/internationalization/i18n.ts
ClientApp/src/internationalization/locales/de.json
ClientApp/src/internationalization/locales/en.json
ClientApp/src/internationalization/locales/es.json
ClientApp/src/internationalization/locales/fr.json
ClientApp/src/internationalization/locales/it.json
ClientApp/src/internationalization/locales/pt.json
ClientApp/src/internationalization/locales/ru.json
ClientApp/src/pages/Settings/General.tsx

- Adds a change language dropdown
- Changed default language to english
Closes https://github.com/lulzsun/RePlays/issues/244

feat: add Change Language dropdown

---

Classes/Recorders/LibObsRecorder.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx
ClientApp/src/internationalization/locales/en.json
ClientApp/src/pages/Settings/Capture.tsx

Allows users to exclusively capture the audio of the recorded game.

feat: Application audio capture

---

Classes/Recorders/LibObsRecorder.cs
Classes/Recorders/PlaysLTCRecorder.cs
Classes/Services/DetectionService.cs
Classes/Services/Keybinds/RecordingKeybind.cs
Classes/Services/RecordingService.cs
Classes/Utils/Helpers.cs
Classes/Utils/JSONObjects.cs
ClientApp/src/index.tsx

Made LibObsRecorder a bit neater by separating StartRecording() into multiple methods.

refactor: LibObsRecorder refactor

---

Classes/Recorders/LibObsRecorder.cs

I don't like this fix, the problem seems to be caused by the session getting out of sync between threads. This should be investigated further.

fix: videoSavePath being null

---

Classes/Integrations/PubgIntegration.cs

- Ensures compatibility with current and future versions by adopting a more dynamic approach.
- Resolves an issue where the Demo directory would not exist when launching the game for the first time after installation.

Update PUBG integration

---

Classes/Services/DetectionService.cs

Games that are distributed through the Microsoft Store/Xbox App that utilize the Microsoft GDK (WinGDK) for Xbox integrations must provide a manifest file called `MicrosoftGame.config`. We can take advantage of that and parse it to get the title for the game.
Note that there are older UWP only games and maybe even current ones that do not use the GDK (or an older version) and therefore do not provide this manifest so we can't detect those (and RePlays can't capture those either so it would be moot).

Implement game name detection for WinGDK aka Xbox games
