lulzsun/RePlays

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/RecordingService.cs
Makes the application feel snappier when launching it (and removes the 2-3 second freeze).
> Loads the recorder asynchronously.

- Classes/Services/Hotkeys/BookmarkHotkey.cs
- Classes/Services/Hotkeys/Hotkey.cs
- Classes/Services/Hotkeys/RecordingHotkey.cs
- Classes/Services/SettingsService.cs
- ClientApp/src/components/HotkeySelector.tsx
- ClientApp/src/index.tsx
- ClientApp/src/pages/Settings.tsx
- ClientApp/src/pages/Settings/Capture.tsx
- ClientApp/src/pages/Settings/Keybindings.tsx
- ClientApp/src/pages/Settings/Upload.tsx
- Added minor fixes to title labels
- Replaced MissingHotkeys with a much better method
- Extracted keybindings to a new settings page
- Changes in "Capture" settings
- Moved "Encoder" to the end of video quality
- Added h1 to Audio settings and renamed the volume types
- Moved "Use Display Capture As Backup" to a new "Advanced" label as I don't think the end user knows what is means
- Added yellow borders while editing keybindings
- Removed a misleading label in "LocalFolder"
> Style: Settings page improvement

- Classes/Services/DetectionService.cs
If accessing the main module's path fails, use a low level approach to gain the file path instead.
> fix: Use a backup method to get file paths in games with anticheat

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/DetectionService.cs
- ClientApp/src/pages/Settings/Detection.tsx
1: Stopped checking for game detections on foreground change as it causes games to be recorded when you alt tab even if you stopped recording.
2: Forced x264 to be added as an available encoder as OBS does not report it
3: Made the blacklist use flex-col
> fix: Various bug fixes

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/DetectionService.cs
Makes a check before changing to display capture to make sure that the user hasn't closed the game within the "retry" 20 seconds.
Fixes #43 .
> FIX: Check if process is still active when changing to display capture.

- Classes/Recorders/LibObsRecorder.cs
- Classes/Utils/JSONObjects.cs
- Classes/Utils/Messages.cs
- ClientApp/src/index.tsx
- ClientApp/src/pages/Settings/Capture.tsx
Allows for selective rate controls. I've only added CBR and VBR since they both work in both CPU and GPU encoders.
Feel free to add more rate controls in the future.
I also changed the default setting to VBR because the CBR uses ALOT more storage and is primary used for streaming ([Source](https://blog.mobcrush.com/using-the-right-rate-control-in-obs-for-streaming-or-recording-4737e22895ed)).
> FEAT: Rate control in settings

- Classes/Recorders/BaseRecorder.cs
- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/DetectionService.cs
This implementation works (surprising) well on all my installed games (Yes, I tested all).
The most significant improvement is the File Description check that checks if the description includes one of the banned words (launcher, splashscreen, cheat), see photo.
> Fixes for multiple splashscreens and AC.

- Classes/Services/DetectionService.cs
My application randomly crashed, so I checked the logs and saw this message:
`[2022-11-10 14:56:33][External Library(0)]: System.IO.FileNotFoundException: C:\PROGRAM FILES\MALWAREBYTES\ANTI-MALWARE\ig-26.exe
at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
at RePlays.Services.DetectionService.AutoDetectGame(Int32 processId, Boolean autoRecord) in D:\Documents\GitHub\RePlays\Classes\Services\DetectionService.cs:line 243
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
`
> Fixed FileNotFoundException

- Classes/Recorders/LibObsRecorder.cs
- Classes/Utils/Helpers.cs
- Displays errors for the user if the recording failed due to: "no space left on device"
- Reverts back to the default storage location if the device has been disconnected
> Storage failure improvements

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/BookmarkService.cs
- Classes/Utils/Helpers.cs
- Classes/Utils/Messages.cs
- Classes/frmMain.cs
**First fix**
The program is mistakenly registering two instances of the game closing. As a result, it is taking the following actions:
1. Retrieve all temporary bookmarks that are meant to be set.
2. Setting the bookmarks as intended.
3. Clearing all temporary bookmarks in preparation for future recordings.
4. Attempting to retrieve all bookmarks again, but since they were cleared in step 3, the result is an empty set.
5. Setting the bookmarks a second time, which overwrites the correct bookmarks set in step 2.
This behavior is causing the program to misbehave, as it is overwriting the correct bookmarks with empty ones.
**Second fix**
You simply can't send a message to webView if it isn't initialized. So I created a backup that gets read when the webView initializes.
> Fix: Bookmarks not working if webView not initialized or gets overwritten

- Classes/Recorders/LibObsRecorder.cs
I have noticed that VBR is recording at a much lower bitrate than I expect.
When set to 15 Mb/s I see my recordings peaking at 5 Mb/s. I do not have this issue with OBS, I believe this might be because I have max bitrate to match bitrate, I figure that max bitrate being unset may be throttling the bitrate in RePlays.
I am unable to test this commit at the moment. I am not familiar with C# or the OBS libraries, however the change I made was very trivial.
If someone could build this for me to test, that would be fab!
> set max_bitrate to match bitrate when using vbr

- Classes/Utils/Helpers.cs
Add 32:9 to the list of valid aspect ratios to support resolutions such as 5120x1440 and 3840x1080. Without this change only a small section of the screen is recorded.
> Add 32:9 as valid resolution for recording games

- Classes/Services/WindowService.cs
Removed Background processes from GetTopLevelWindows. This should reduce lag during startup.
> Remove Background processes from GetTopLevelWindows

- ClientApp/src/components/AudioDevice.tsx
- ClientApp/src/pages/Settings/Capture.tsx
Removed the possibility to delete the `default device` if it's the only one selected. You can still remove the `default device` if there is another item in the input/output.
> fix: Fixed input/output removability

- Classes/Services/KeybindService.cs
- Made it possible to press the keybinding while holding another key*
- Improved speed from `O(n log n) + O(m)` to `O(n)`
\* This is useful when you might already be holding down keys for other actions (e.g., sneaking with `CTRL`) and wish to trigger the bookmark (with `F8`) without needing to release the `CTRL` key.
> refactor: Keybinding improvements

- ClientApp/src/components/Bookmark.tsx
- ClientApp/src/pages/Player.tsx
This fix addresses a problem where users couldn't drag clips. The problem started after a change I made in https://github.com/lulzsun/RePlays/pull/176. To solve this, a new bookmark class is added, and the code now checks against this class instead.
> fix: non draggable clips

- Classes/Utils/Messages.cs
My bad.
Fixes an issue where we run the Environment.ProcessPath (`%localappdata%\RePlays\app-1.3.5\RePlays.exe`) after update instead of `%localappdata%\RePlays\RePlays.exe`.
> fix: Application path on update

- Classes/Services/DetectionService.cs
The issue where games on the whitelist are being saved under the name "Whitelist Mode" has been fixed.
> fix: Games on the whitelist are being saved under the name "Whitelist Mode"

- Classes/Services/DetectionService.cs
Fixes an issue where games not registered in the whitelist were being recorded, despite the whitelist mode.
Currently:
> fix: Skip recording for non-matched games in whitelist mode

- Classes/Integrations/LeagueOfLegendsIntegration.cs
- Classes/Utils/JSONObjects.cs
- ClientApp/src/components/Card.tsx
- ClientApp/src/integrations/league.ts
- ClientApp/src/pages/VideosPage.tsx
- Corrected incorrect labeling of League of Legends games as Losses
- Retrieve latest LOL update only if user has a LOL recording
Partially fixes #216: It is not possible to retrieve the win-status if the user has used ALT+F4 to exit the game as the Live Game Data API has been shut down.
> fix: correct incorrect labeling of League of Legends games as Losses

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/SettingsService.cs
- Classes/Utils/JSONObjects.cs
- ClientApp/src/index.tsx
- ClientApp/src/pages/Settings/Capture.tsx
- Automatically falls back to .mp4 if an incompatible file format is chosen when enabling the replay buffer
- Only show compatible file formats in the File Format dropdown
Fixes #207.
> fix: disable incompatible replay buffer flow file formats (#207)

- Classes/Utils/Helpers.cs
I'm not sure how I overlooked this
> fix: show no error message on successful clip creation with re-encode

- Classes/Recorders/LibObsRecorder.cs
- Classes/Utils/JSONObjects.cs
Multiple Discord users report being unable to record, and it appears they are somehow bypassing the default behavior that sets the file format to MP4 when Replay Buffer is enabled. This is a (hacky) fix to default to MP4.
> fix: Default to mp4 if Replay Buffer and incompatible file format

- Classes/Services/DetectionService.cs
Use game's executable as Game Title as a last resort instead of Game Unknown when the game's title is undetected.
Basically meant for non Steam games.
This way, a bunch of undetected games don't get lumped under one single game entry.
That said, I'm going to work on implementing detection for Xbox/GamePass games (not the early UWP ones).
> Use game's executable as Game Title as a last resort

- Classes/Recorders/LibObsRecorder.cs
- Classes/Services/WindowService.cs
Related issue: #180 
Currently, recording an HDR game with RePlays results in the recording having washed out colors.
This commit adds a detection feature for Windows on whether the current monitor has HDR
enabled, and if so, changes the color space of the capture to an appropriate one for HDR.
The resulting recording is still SDR but tonemapped from HDR. Essentially, this is the same as
setting the property `RGB10A2 Color Space` to `Rec. 2100 (PQ)` on OBS on a game capture source.
The bulk of the code is on just detecting if HDR is enabled. I placed it in WindowService because
it already has display/monitor related code. Should it be spun into its own class?
When setting the brightness levels for the capture, I hardcoded the default OBS values of 300 and 1000,
which to me produce …
> feat: Record and tonemap HDR content (issue #180)
